sonar.projectKey=edupulse
sonar.projectName=EduPulse
sonar.projectVersion=0.1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/.next/**,**/node_modules/**,**/public/**
sonar.typescript.tsconfigPath=tsconfig.json
