apiVersion: v1
kind: Secret
metadata:
  name: edupulse-secrets
  namespace: edupulse
type: Opaque
stringData:
  POSTGRES_USER: "edupulse"
  POSTGRES_PASSWORD: "change-me"
  POSTGRES_DB: "edupulse"
  DATABASE_URL: "postgresql://edupulse:change-me@edupulse-postgres:5432/edupulse?schema=public"
  NEXTAUTH_SECRET: "replace-with-a-secure-random-string"
