apiVersion: v1
kind: Secret
metadata:
  name: edupulse-secrets
  namespace: edupulse
type: Opaque
stringData:
  DATABASE_URL: "postgresql://edupulse:edupulse@edupulse-postgres:5432/edupulse?schema=public"
  NEXTAUTH_SECRET: "6aJ3sevkxA0TsH/smkF7iLrWwG4TYpyI4YbE46yvRVk="
  POSTGRES_USER: "edupulse"
  POSTGRES_PASSWORD: "edupulse"
  POSTGRES_DB: "edupulse"
